### Endpoint GET /users
GET http://localhost:3000/users/

### Enpoinrt POST /users
POST http://localhost:3000/users
content-type: application/json

{
    "id": 10,
    "name": "John Smith"
}

### Endpoint put /users
PUT http://localhost:3000/users/1
content-type: application/json

{
    "name": "John Adit"
}

### Endpoint delete /users
DELETE http://localhost:3000/users/1
content-type: application/json


### Endpoint register /auth
POST http://localhost:3000/api/v1/auth/register
content-type: application/json

{
    "username": "Pablo",
    "password": "testing123"
}

### Endpoint login /auth
POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
    "username": "Pablo",
    "password": "testing123"
}

### Enpoint profile /auth
GET http://localhost:3000/api/v1/auth/profile
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInVzZXJuYW1lIjoiUGFibG8iLCJwYXNzd29yZCI6InRlc3RpbmcxMjMiLCJpYXQiOjE2Mjg1NjEwMzl9.X1_jOeATS4cAVYjUDYeDVakmE1jiXHmqwjqYVCLKgbM


### Endpoint GET todos /todos
GET http://localhost:3000/api/v1/todos
content-type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInVzZXJuYW1lIjoiUGFibG8iLCJwYXNzd29yZCI6InRlc3RpbmcxMjMiLCJpYXQiOjE2Mjg1Njg2MDB9.w11DOet4thBUjdtLHZE-D3mypEm7xZjLTM2H8Q7yoKo


### Endpoint POST todos /todos
POST http://localhost:3000/api/v1/todos
content-type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInVzZXJuYW1lIjoiUGFibG8iLCJwYXNzd29yZCI6InRlc3RpbmcxMjMiLCJpYXQiOjE2Mjg1Njg2MDB9.w11DOet4thBUjdtLHZE-D3mypEm7xZjLTM2H8Q7yoKo

{
    "description":"testing post pertama saya"
}